// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: demo

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
lv_obj_set_width( ui_Keyboard1, 234);
lv_obj_set_height( ui_Keyboard1, 120);
lv_obj_set_x( ui_Keyboard1, 0 );
lv_obj_set_y( ui_Keyboard1, 97 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

ui_Spinner1 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner1, 80);
lv_obj_set_height( ui_Spinner1, 80);
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags


}
